export const mockProjectCards = [
    {
        id: 1,
        name: 'Project Card 1',
        description: 'Project Description 1',
        project_id: 1,
        project_board_id: 1,
        task_Categories_id: 1,
        profile_id: 1,
        updated_by: 1,
        is_approved: false,
        is_archived: false,
    },
    {
        id: 1,
        name: 'Project Card 2',
        description: 'Project Description 2',
        project_id: 1,
        project_board_id: 1,
        task_Categories_id: 1,
        profile_id: 1,
        updated_by: 1,
        is_approved: false,
        is_archived: false,
    },
    {
        id: 1,
        name: 'Project Card 3',
        description: 'Project Description 3',
        project_id: 1,
        project_board_id: 1,
        task_Categories_id: 1,
        profile_id: 1,
        updated_by: 1,
        is_approved: false,
        is_archived: false,
    },
]