export const mockProjects = [
        {
            id: '1',
            name: "E-commerce Platform",
            description: "Building a modern e-commerce platform with React and Node.js",
            team_id: 1,
            is_archived: false,
            project_logo: "https://img.freepik.com/free-vector/ecommerce-web-page-concept-illustration_114360-8204.jpg",
            created_at: "2025-01-15T10:00:00Z",
        }, 
        {
            id: 2,
            name: "Mobile Banking App",
            description: "Secure mobile banking application with advanced security features",
            team_id: 1,
            is_archived: false,
            project_logo: "https://img.freepik.com/free-vector/mobile-banking-concept-illustration_114360-5180.jpg",
            created_at: "2025-01-12T10:00:00Z",
        }, 
        {
            id: 3,
            name: "Design System",
            description: "Comprehensive design system for consistent UI components",
            team_id: 2,
            is_archived: false,
            project_logo: "https://img.freepik.com/free-vector/design-system-concept-illustration_114360-1542.jpg",
            created_at: "2025-01-10T10:00:00Z",
        }, 
        {
            id: 4,
            name: "Brand Identity Refresh",
            description: "Complete brand identity overhaul for modern look and feel",
            team_id: 2,
            is_archived: true,
            project_logo: "https://img.freepik.com/free-vector/brand-identity-concept-illustration_114360-1285.jpg",
            created_at: "2025-01-05T10:00:00Z",
        }, 
        {
            id: 5,
            name: "Social Media Campaign",
            description: "Multi-platform social media campaign for product launch",
            team_id: 3,
            is_archived: false,
            project_logo: "https://img.freepik.com/free-vector/social-media-marketing-concept-illustration_114360-1003.jpg",
            created_at: "2025-01-08T10:00:00Z",
        },
        {
            id: 6,
            name: "Customer Analytics Dashboard",
            description: "Real-time analytics dashboard for customer behavior insights",
            team_id: 4,
            is_archived: false,
            project_logo: "https://img.freepik.com/free-vector/analytics-concept-illustration_114360-1142.jpg",
            created_at: "2025-01-12T10:00:00Z",
        }, 
        {
            id: 7,
            name: "AI Recommendation Engine",
            description: "Machine learning powered recommendation system",
            team_id: 4,
            is_archived: true,
            project_logo: "https://img.freepik.com/free-vector/artificial-intelligence-concept-illustration_114360-5215.jpg",
            created_at: "2025-01-03T10:00:00Z",
        }, 
        {
            id: 8,
            name: "Automated Testing Suite",
            description: "Comprehensive automated testing framework for all applications",
            team_id: 5,
            is_archived: false,
            project_logo: "https://img.freepik.com/free-vector/automated-testing-concept-illustration_114360-1492.jpg",
            created_at: "2025-01-14T10:00:00Z",
        },
        {
            id: 9,
            name: "Cloud Infrastructure Setup",
            description: "Scalable cloud infrastructure with monitoring and deployment pipelines",
            team_id: 6,
            is_archived: false,
            project_logo: "https://img.freepik.com/free-vector/cloud-computing-concept-illustration_114360-1021.jpg",
            created_at: "2025-01-11T10:00:00Z",
        }
    ]